parameters:
#   Drupal users authenticate as Symfony users and are part of sessions.
    bangpound_drupal.handler.session.class: Bangpound\Bundle\DrupalBundle\DrupalSessionHandler
    bangpound_drupal.user_provider.class: Bangpound\Bundle\DrupalBundle\Security\User\UserProvider
    bangpound_drupal.encoder.class: Bangpound\Bundle\DrupalBundle\Security\Encoder\PasswordEncoder
    bangpound_drupal.hashed_password_authenticator.class: Bangpound\Bundle\DrupalBundle\Security\Authentication\HashedPasswordAuthenticator

#   These events and functions trigger the Drupal module API because the Drupal submit handlers are completely
#   irrelevant.
    bangpound_drupal.listener.authentication.class: Bangpound\Bundle\DrupalBundle\EventListener\AuthenticationListener
    bangpound_drupal.logout.handler.class: Bangpound\Bundle\DrupalBundle\Security\LogoutHandler

services:
    bangpound_drupal.hashed_password_authenticator:
        class:     %bangpound_drupal.hashed_password_authenticator.class%

    bangpound_drupal.listener.authentication:
        class: %bangpound_drupal.listener.authentication.class%
        arguments: [ @request_stack ]
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }

    bangpound_drupal.logout.handler:
        class: %bangpound_drupal.logout.handler.class%

    bangpound_drupal.handler.session:
        class: %bangpound_drupal.handler.session.class%

    bangpound_drupal.user_provider:
        class: %bangpound_drupal.user_provider.class%

    bangpound_drupal.encoder:
        class: %bangpound_drupal.encoder.class%
        arguments: [ @bangpound_drupal.bootstrap ]
