parameters:
#   Fundamental HttpKernel components that turn Drupal page callbacks into Symfony controllers.
    bangpound_drupal.http_kernel.class:            Bangpound\LegacyPhp\DependencyInjection\ContainerAwareHttpKernel

    bangpound_drupal.listener.controller.class:    Bangpound\Bridge\Drupal\EventListener\ControllerListener
    bangpound_drupal.listener.shutdown.class:      Bangpound\LegacyPhp\EventListener\ShutdownListener
    bangpound_drupal.listener.output_buffer.class: Bangpound\LegacyPhp\EventListener\OutputBufferListener
    bangpound_drupal.listener.header.class:        Bangpound\LegacyPhp\EventListener\HeaderListener

services:
    bangpound_drupal.request_matcher:
        class:  %bangpound_drupal.request_matcher.class%
        calls:
            - [ matchAttribute, [ '_legacy', 'drupal' ] ]

    bangpound_drupal.listener.controller:
        class: %bangpound_drupal.listener.controller.class%
        arguments: [ @bangpound_drupal.request_matcher ]
        tags:
            - { name: kernel.event_subscriber }

    bangpound_drupal.listener.shutdown:
        class: %bangpound_drupal.listener.shutdown.class%
        arguments: [ @bangpound_drupal.request_matcher ]
        tags:
            - { name: kernel.event_subscriber }

    bangpound_drupal.listener.output_buffer:
        class: %bangpound_drupal.listener.output_buffer.class%
        arguments: [ @bangpound_drupal.request_matcher, @legacy.response ]
        tags:
            - { name: kernel.event_subscriber }

    bangpound_drupal.listener.header:
        class: %bangpound_drupal.listener.header.class%
        arguments: [ @bangpound_drupal.request_matcher ]
        tags:
            - { name: kernel.event_subscriber }

    legacy.response:
        class: Symfony\Component\HttpFoundation\Response
