bangpound_drupal_ctools_content_types:
    resource: "@BangpoundDrupalBundle/Controller/CtoolsContentTypesController.php"
    type:     annotation

bangpound_drupal_entity:
    resource: "@BangpoundDrupalBundle/Controller/EntityController.php"
    type:     annotation
