imports:
    - { resource: http_kernel.yml }
    - { resource: bootstrap.yml }
    - { resource: firewall.yml }
    - { resource: twig.yml }

parameters:

    bangpound_drupal.response.class:  Symfony\Component\HttpFoundation\Response
    bangpound_drupal.request_matcher.class: Symfony\Component\HttpFoundation\RequestMatcher
    bangpound_drupal.router.class: Bangpound\Bundle\DrupalBundle\Routing\DrupalRouter

#   Request, View and Shutdown listener integrate Symfony and Drupal 7.
    bangpound_drupal.listener.request.class: Bangpound\Bundle\DrupalBundle\EventListener\RequestListener


#   Pluggable parts of Drupal that are replaced by Symfony components.
    bangpound_drupal.conf.session_inc: sites/all/modules/symfony-module/session.inc
    bangpound_drupal.conf.mail_system.default_system: Bangpound\Bridge\Drupal\SwiftMailSystem

#   Controller parameter converter for Entities.
    bangpound_drupal.converter.drupal_entity.class: Bangpound\Bundle\DrupalBundle\ParamConverter\EntityParamConverter

    bangpound_drupal.drush_command.class: Bangpound\Bundle\DrupalBundle\Command\DrushCommand

    bangpound_drupal.drufony.class: Drufony

services:
    bangpound_drupal.response:
        scope: request
        class: %bangpound_drupal.response.class%

    bangpound_drupal.listener.request:
        class: %bangpound_drupal.listener.request.class%
        arguments: [ @bangpound_drupal.request_matcher ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -1024 }

    bangpound_drupal.converter.drupal_entity:
        class: %bangpound_drupal.converter.drupal_entity.class%
        tags:
            - { name: request.param_converter, converter: drupal.entity }

    bangpound_drupal.router:
        class: %bangpound_drupal.router.class%
        tags:
            - { name: router }

    bangpound_drupal.drush_command:
        class: %bangpound_drupal.drush_command.class%
        tags:
            - { name: console.command }

    bangpound_drupal.drufony:
        class: %bangpound_drupal.drufony.class%
        calls:
            - [ 'setContainer', [ @service_container ] ]
