parameters:
    bangpound_drupal.http_kernel.class: Bangpound\Bundle\DrupalBundle\DependencyInjection\ContainerAwareLegacyPhpHttpKernel
    bangpound_drupal.controller_resolver.class: Bangpound\Bundle\DrupalBundle\Controller\ControllerResolver
    bangpound_drupal.response.class: Symfony\Component\HttpFoundation\Response
    bangpound_drupal.listener.request.class: Bangpound\Bundle\DrupalBundle\EventListener\RequestListener
    bangpound_drupal.listener.path.class: Bangpound\Bundle\DrupalBundle\EventListener\PathListener
    bangpound_drupal.listener.view.class: Bangpound\Bundle\DrupalBundle\EventListener\ViewListener
    bangpound_drupal.routing_loader.class: Bangpound\Bundle\DrupalBundle\Routing\DrupalLoader
    bangpound_drupal.listener.shutdown.class: Bangpound\Bundle\DrupalBundle\EventListener\ShutdownListener
    bangpound_drupal.globals.class: Bangpound\Bundle\DrupalBundle\Globals
    bangpound_drupal.bootstrap.class: Bangpound\Bundle\DrupalBundle\Bootstrap
    bangpound_drupal.handler.session.class: Bangpound\Bundle\DrupalBundle\DrupalSessionHandler
    bangpound_drupal.user_provider.class: Bangpound\Bundle\DrupalBundle\Security\User\UserProvider
    bangpound_drupal.encoder.class: Bangpound\Bundle\DrupalBundle\Security\Encoder\PasswordEncoder
    bangpound_drupal.twig.render_extension.class: Bangpound\Bundle\DrupalBundle\Twig\RenderExtension
    bangpound_drupal.twig.theme_extension.class: Bangpound\Bundle\DrupalBundle\Twig\ThemeExtension
    bangpound_drupal.listener.user.class: Bangpound\Bundle\DrupalBundle\EventListener\UserListener
    bangpound_drupal.listener.authentication.class: Bangpound\Bundle\DrupalBundle\EventListener\AuthenticationListener
    bangpound_drupal.conf.session_inc: sites/all/modules/symfony-module/session.inc
    bangpound_drupal.conf.mail_system.default_system: Bangpound\Bundle\DrupalBundle\SwiftMailSystem
    bangpound_drupal.converter.drupal_entity.class: Bangpound\Bundle\DrupalBundle\ParamConverter\EntityParamConverter
    bangpound_drupal.logout.handler.class: Bangpound\Bundle\DrupalBundle\Security\LogoutHandler

services:
    bangpound_drupal.response:
        class: %bangpound_drupal.response.class%

    bangpound_drupal.listener.user:
        class: %bangpound_drupal.listener.user.class%
        arguments: [ @security.context ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 32 }

    bangpound_drupal.listener.path:
        class: %bangpound_drupal.listener.path.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    bangpound_drupal.listener.request:
        class: %bangpound_drupal.listener.request.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    bangpound_drupal.listener.view:
        class: %bangpound_drupal.listener.view.class%
        calls:
            - [ 'setContainer', [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    bangpound_drupal.listener.shutdown:
        class: %bangpound_drupal.listener.shutdown.class%
        calls:
            - [ 'setContainer', [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 31 }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 512 }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 512 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelPostController, priority: 512 }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate, priority: 512 }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelPostController, priority: 512 }

    bangpound_drupal.routing_loader:
        class: %bangpound_drupal.routing_loader.class%
        tags:
            - { name: routing.loader }

    bangpound_drupal.handler.session:
        class: %bangpound_drupal.handler.session.class%
        arguments: [ @session.handler.native_file ]

    bangpound_drupal.globals:
        class: %bangpound_drupal.globals.class%
        calls:
            - [ 'offsetSet', ['response', @bangpound_drupal.response ] ]
            - [ 'offsetSet', ['session', @session ] ]
            - [ 'offsetSet', ['service_container', @service_container ] ]

    bangpound_drupal.user_provider:
        class: %bangpound_drupal.user_provider.class%

    bangpound_drupal.encoder:
        class: %bangpound_drupal.encoder.class%

    bangpound_drupal.twig.render_extension:
        class: %bangpound_drupal.twig.render_extension.class%
        tags:
            - { name: twig.extension }

    bangpound_drupal.twig.theme_extension:
        class: %bangpound_drupal.twig.theme_extension.class%
        tags:
            - { name: twig.extension }

    bangpound_drupal.listener.authentication:
        class: %bangpound_drupal.listener.authentication.class%
        arguments: [ @request_stack ]
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }

    bangpound_drupal.logout.handler:
        class: %bangpound_drupal.logout.handler.class%

    bangpound_drupal.converter.drupal_entity:
        class: %bangpound_drupal.converter.drupal_entity.class%
        tags:
            - { name: request.param_converter, converter: drupal.entity }
