imports:
    - { resource: http_kernel.yml }
    - { resource: bootstrap.yml }
    - { resource: firewall.yml }
    - { resource: twig.yml }

parameters:
    bangpound_drupal.response.class:  Symfony\Component\HttpFoundation\Response
    bangpound_drupal.request_matcher.class: Symfony\Component\HttpFoundation\RequestMatcher
    bangpound_drupal.router.class: Bangpound\Bundle\DrupalBundle\Routing\DrupalRouter

#   Controller parameter converter for Entities.
    bangpound_drupal.converter.drupal_entity.class: Bangpound\Bundle\DrupalBundle\ParamConverter\EntityParamConverter

    bangpound_drupal.drush_command.class: Bangpound\Bundle\DrupalBundle\Command\DrushCommand

    bangpound_drupal.drufony.class: Drufony

    bangpound_drupal.mail_system.class: Bangpound\Bundle\DrupalBundle\SwiftMailSystem

    bangpound_drupal.controller.class: Bangpound\Bridge\Drupal\Controller\Controller

    bangpound_drupal.converter.router_item.class: Bangpound\Bridge\Drupal\ParamConverter\RouterItemConverter

services:
    bangpound_drupal.converter.drupal_entity:
        class: %bangpound_drupal.converter.drupal_entity.class%
        tags:
            - { name: request.param_converter, converter: drupal.entity }

    bangpound_drupal.converter.router_item:
        class: %bangpound_drupal.converter.router_item.class%
        tags:
            - { name: request.param_converter, converter: drupal.router_item }

    bangpound_drupal.router:
        class: %bangpound_drupal.router.class%
        arguments: [ @bangpound_drupal.bootstrap ]
        tags:
            - { name: router }

    bangpound_drupal.drush_command:
        class: %bangpound_drupal.drush_command.class%
        tags:
            - { name: console.command }

    bangpound_drupal.drufony:
        class: %bangpound_drupal.drufony.class%
        calls:
            - [ 'setContainer', [ @service_container ] ]

    bangpound_drupal.mail_system:
        class: %bangpound_drupal.mail_system.class%

    bangpound_drupal.controller:
        class: %bangpound_drupal.controller.class%
