parameters:
#   Twig extensions to replicate Drupal 7 render and theme functions.
    bangpound_drupal.twig.render_extension.class: Bangpound\Bundle\DrupalBundle\Twig\RenderExtension
    bangpound_drupal.twig.theme_extension.class: Bangpound\Bundle\DrupalBundle\Twig\ThemeExtension
    bangpound_drupal.twig.toolbar_extension.class: Bangpound\Bundle\DrupalBundle\Twig\ToolbarExtension


services:
    bangpound_drupal.twig.render_extension:
        class: %bangpound_drupal.twig.render_extension.class%
        tags:
            - { name: twig.extension }

    bangpound_drupal.twig.theme_extension:
        class: %bangpound_drupal.twig.theme_extension.class%
        tags:
            - { name: twig.extension }

    bangpound_drupal.twig.toolbar_extension:
        class: %bangpound_drupal.twig.toolbar_extension.class%
        arguments: [ @request_stack, @bangpound_drupal.bootstrap ]
        tags:
            - { name: twig.extension }
